# Generated by Django 2.1.2 on 2018-10-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='股票代码')),
                ('name', models.CharField(max_length=30, verbose_name='股票名称')),
                ('mark', models.CharField(max_length=200, verbose_name='股票备注')),
            ],
        ),
    ]
