# Generated by Django 2.1.1 on 2018-10-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrontabAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='执行时间')),
                ('name', models.CharField(max_length=30, verbose_name='任务名称')),
                ('description', models.CharField(max_length=100, verbose_name='任务描述')),
            ],
        ),
    ]
