# Generated by Django 2.1.1 on 2018-10-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_crontabaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='mark',
            field=models.CharField(max_length=200, null=True, verbose_name='股票备注'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='股票名称'),
        ),
    ]
