# Generated by Django 2.1.1 on 2018-10-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20181008_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_interest',
            field=models.BooleanField(default=False, verbose_name='是否关注'),
        ),
    ]
